apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    team: {{ .Values.team.name }}
    app: {{ .Values.app.name }}
spec:
  ports:
    - name: web
      port: 8080
      targetPort: web
  selector:
    team: {{ .Values.team.name }}
    app: {{ .Values.app.name }}