apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: 1.24.3
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress