apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokemon-trainer
spec:
  project: default
  source:
    path: pokemon-trainer
    repoURL: https://github.com/eroznik/apps.git
    targetRevision: test-ld
  destination:
    server: https://kubernetes.default.svc
    namespace: pokemon-world
